# Generated by Django 6.0.6 on 2026-06-29 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MpcProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpc_product_category_name', models.CharField(help_text='The unique name of the product category.', max_length=100, unique=True)),
                ('mpc_product_category_slug', models.SlugField(blank=True, help_text='URL-friendly slug. Leaves blank to auto-generate from the name.', max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'MPC Product Category',
                'verbose_name_plural': 'MPC Product Categories',
                'ordering': ['mpc_product_category_name'],
            },
        ),
        migrations.CreateModel(
            name='MpcProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpc_product_name', models.CharField(max_length=200, unique=True)),
                ('mpc_product_slug', models.SlugField(blank=True, help_text='Leave blank to auto-generate from product name.', max_length=220, unique=True)),
                ('mpc_product_price', models.DecimalField(decimal_places=2, help_text='Price in TZS.', max_digits=10)),
                ('mpc_products_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OUT_OF_STOCK', 'Out of Stock'), ('DRAFT', 'Draft / Hidden')], default='AVAILABLE', max_length=20)),
                ('mpc_product_unit', models.CharField(choices=[('kg', 'Kilogram (kg)'), ('pc', 'Piece (pc)'), ('L', 'Liter (L)')], default='pc', max_length=5)),
                ('mpc_product_details', models.TextField(help_text='Detailed description of the product.')),
                ('mpc_products_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='mpc_products.mpcproductcategory')),
            ],
            options={
                'verbose_name': 'MPC Product',
                'verbose_name_plural': 'MPC Products',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MpcProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/')),
                ('is_feature_image', models.BooleanField(default=False, help_text='Check this to make it the primary image for the product.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpc_products_images', to='mpc_products.mpcproduct')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['-is_feature_image', '-created_at'],
            },
        ),
    ]
